version: '3'
services:
  runner:
    image: otpmail
    env_file: ./.env
    #networks:
    #  - traefik-public
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 150M

#networks:
#  traefik-public:
#    external: true
